---
php_packages: [ "php7.4", "php7.4-mysql", "php7.4-soap", "php7.4-bcmath", "php7.4-xml", "php7.4-mbstring", "php7.4-gd", "php7.4-common", "php7.4-cli", "php7.4-curl", "php7.4-intl", "php7.4-zip", "zip", "unzip" ]
php_file_uploads: "On"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"
php_post_max_size: "32M"
